export enum PartyDocumentType {
  DON_XIN_VAO_DANG = "DON_XIN_VAO_DANG",
  GIAY_GIOI_THIEU_DANG_VIEN1 = "GIAY_GIOI_THIEU_DANG_VIEN1",
  GIAY_GIOI_THIEU_DANG_VIEN2 = "GIAY_GIOI_THIEU_DANG_VIEN2",
  LY_LICH_XIN_VAO_DANG = "LY_LICH_XIN_VAO_DANG",
  NHAN_XET_DOAN_THE = "NHAN_XET_DOAN_THE",
  NGHI_QUYET_CHI_BO = "NGHI_QUYET_CHI_BO",
}