export enum AdmissionStepCode {
    APPLICATION = "APPLICATION",
    TRAINING_CLASS = "TRAINING_CLASS",
    VERIFICATION = "VERIFICATION",
    UNION_FEEDBACK = "UNION_FEEDBACK",
    FINAL_REVIEW = "FINAL_REVIEW",
    CEREMONY = "CEREMONY",
}