export enum AdmissionLogAction {
  CREATE_APPLICATION_DRAFT = 'CREATE_APPLICATION_DRAFT',
  UPDATE_APPLICATION_DRAFT = 'UPDATE_APPLICATION_DRAFT',
  SUBMIT_APPLICATION = 'SUBMIT_APPLICATION',
  UPLOAD_APPLICATION_ATTACHMENT = 'UPLOAD_APPLICATION_ATTACHMENT',
}
