export enum PartyAdmissionAssignmentRole {
    CHI_UY_REVIEWER = "CHI_UY_REVIEWER",
    PBT_REVIEWER = "PBT_REVIEWER",
    RED_SEAL_CHECKER = "RED_SEAL_CHECKER",
    RESOLUTION_DRAFTER = "RESOLUTION_DRAFTER",
    SECRETARY_APPROVER = "SECRETARY_APPROVER",
  }