export enum PartyAdmissionWorkflowAction {
    CREATE_DRAFT = "CREATE_DRAFT",
    UPDATE_DRAFT = "UPDATE_DRAFT",
    SUBMIT = "SUBMIT",
    REQUEST_SUPPLEMENT = "REQUEST_SUPPLEMENT",
    RESUBMIT = "RESUBMIT",
  
    FORWARD_TO_PBT = "FORWARD_TO_PBT",
    APPROVE_CONTENT = "APPROVE_CONTENT",
    REJECT_CONTENT = "REJECT_CONTENT",
  
    SUBMIT_LOCAL_VERIFICATION = "SUBMIT_LOCAL_VERIFICATION",
    APPROVE_RED_SEAL = "APPROVE_RED_SEAL",
    REJECT_RED_SEAL = "REJECT_RED_SEAL",
  
    SUBMIT_RESOLUTION_DRAFT = "SUBMIT_RESOLUTION_DRAFT",
    APPROVE_RESOLUTION = "APPROVE_RESOLUTION",
    REQUEST_RESOLUTION_REVISION = "REQUEST_RESOLUTION_REVISION",
  
    CANCEL = "CANCEL",
    COMPLETE = "COMPLETE",
  }