import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1774781271619 implements MigrationInterface {
    name = 'Migrations1774781271619'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "party_admission_workflow_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicationId" uuid NOT NULL, "stepId" uuid, "action" character varying(100) NOT NULL, "fromStatus" character varying(50), "toStatus" character varying(50), "fromStepCode" character varying(50), "toStepCode" character varying(50), "message" text, "metadata" jsonb, "actorId" uuid, "actorRole" character varying(50), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1eb3557d8ed921c308c3dfb40b0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_party_admission_workflow_logs_step_id" ON "party_admission_workflow_logs" ("stepId") `);
        await queryRunner.query(`CREATE INDEX "idx_party_admission_workflow_logs_application_id" ON "party_admission_workflow_logs" ("applicationId") `);
        await queryRunner.query(`CREATE TYPE "public"."party_admission_steps_stepcode_enum" AS ENUM('APPLICATION', 'TRAINING_CLASS', 'VERIFICATION', 'UNION_FEEDBACK', 'FINAL_REVIEW', 'CEREMONY')`);
        await queryRunner.query(`CREATE TYPE "public"."party_admission_steps_status_enum" AS ENUM('LOCKED', 'DRAFT', 'OPEN', 'IN_PROGRESS', 'PENDING_APPROVAL', 'COMPLETED', 'RETURNED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "party_admission_steps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicationId" uuid NOT NULL, "stepCode" "public"."party_admission_steps_stepcode_enum" NOT NULL, "stepName" character varying(100) NOT NULL, "stepOrder" integer NOT NULL, "status" "public"."party_admission_steps_status_enum" NOT NULL DEFAULT 'LOCKED', "isLocked" boolean NOT NULL DEFAULT false, "isCurrent" boolean NOT NULL DEFAULT false, "isCompleted" boolean NOT NULL DEFAULT false, "openedAt" TIMESTAMP, "submittedAt" TIMESTAMP, "approvedAt" TIMESTAMP, "returnedAt" TIMESTAMP, "rejectedAt" TIMESTAMP, "returnReason" text, "approvedById" uuid, "returnedById" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_party_admission_steps_application_step_code" UNIQUE ("applicationId", "stepCode"), CONSTRAINT "PK_7f20e99549868879194f3ccba3c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_party_admission_steps_status" ON "party_admission_steps" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_party_admission_steps_application_id" ON "party_admission_steps" ("applicationId") `);
        await queryRunner.query(`CREATE TYPE "public"."party_admission_step_submissions_stepcode_enum" AS ENUM('APPLICATION', 'TRAINING_CLASS', 'VERIFICATION', 'UNION_FEEDBACK', 'FINAL_REVIEW', 'CEREMONY')`);
        await queryRunner.query(`CREATE TYPE "public"."party_admission_step_submissions_status_enum" AS ENUM('LOCKED', 'DRAFT', 'OPEN', 'IN_PROGRESS', 'PENDING_APPROVAL', 'COMPLETED', 'RETURNED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "party_admission_step_submissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicationId" uuid NOT NULL, "stepId" uuid NOT NULL, "stepCode" "public"."party_admission_step_submissions_stepcode_enum" NOT NULL, "version" integer NOT NULL DEFAULT '1', "status" "public"."party_admission_step_submissions_status_enum" NOT NULL DEFAULT 'DRAFT', "formData" jsonb, "note" text, "submittedById" uuid, "submittedAt" TIMESTAMP, "isLatest" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1233c449c286bb9d639ee8ede89" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_party_admission_step_submissions_step_id" ON "party_admission_step_submissions" ("stepId") `);
        await queryRunner.query(`CREATE INDEX "idx_party_admission_step_submissions_application_id" ON "party_admission_step_submissions" ("applicationId") `);
        await queryRunner.query(`CREATE TYPE "public"."party_admission_documents_documenttype_enum" AS ENUM('LY_LICH', 'DON_XIN_VAO_DANG', 'LY_LICH_NGUOI_XIN_VAO_DANG', 'GIAY_GIOI_THIEU_DANG_VIEN_1', 'GIAY_GIOI_THIEU_DANG_VIEN_2', 'NGHI_QUYET_CHI_DOAN', 'XAC_MINH_DIA_PHUONG', 'NGHI_QUYET_KET_NAP_DU_THAO', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "party_admission_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "applicationId" uuid NOT NULL, "stepId" uuid, "submissionId" uuid, "documentType" "public"."party_admission_documents_documenttype_enum" NOT NULL, "originalFileName" character varying(255) NOT NULL, "storedFileName" character varying(255) NOT NULL, "objectKey" character varying(500) NOT NULL, "mimeType" character varying(100), "size" bigint, "version" integer NOT NULL DEFAULT '1', "isLatest" boolean NOT NULL DEFAULT true, "uploadedById" uuid, "uploadedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ac0ddf38373b591e84766929b5d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_party_admission_documents_submission_id" ON "party_admission_documents" ("submissionId") `);
        await queryRunner.query(`CREATE INDEX "idx_party_admission_documents_step_id" ON "party_admission_documents" ("stepId") `);
        await queryRunner.query(`CREATE INDEX "idx_party_admission_documents_application_id" ON "party_admission_documents" ("applicationId") `);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "meeting_sessions" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "meeting_sessions" DROP CONSTRAINT "FK_79bd95834df6a4229d47c89ddc9"`);
        await queryRunner.query(`ALTER TABLE "meeting_attendees" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "meeting_opinions" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "meeting_opinions" DROP CONSTRAINT "FK_b37b346f4b2304af77b536431ab"`);
        await queryRunner.query(`ALTER TABLE "meeting_attendees" DROP CONSTRAINT "FK_8643679c49d7234b266433bc201"`);
        await queryRunner.query(`ALTER TABLE "meeting_documents" DROP CONSTRAINT "FK_71ce465252b5177f3a8734a66de"`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "party_member_positions" DROP CONSTRAINT "FK_2b3335beefdad662520afc33dc8"`);
        await queryRunner.query(`ALTER TABLE "ai_knowledge_base" DROP CONSTRAINT "FK_fa554fa15e67675623cdecf80a1"`);
        await queryRunner.query(`ALTER TABLE "meetings" DROP CONSTRAINT "FK_5d9e6ff1adcbd2c4b1251646a79"`);
        await queryRunner.query(`ALTER TABLE "party_members" DROP CONSTRAINT "FK_59fcd9e0286d8c9009113772e5d"`);
        await queryRunner.query(`ALTER TABLE "party_admissions" DROP CONSTRAINT "FK_52e8c691a7e540ba4502ef6e380"`);
        await queryRunner.query(`ALTER TABLE "party_cells" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "admission_progress" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "party_fees" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "annual_assessments" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "commendations" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "disciplines" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "party_member_positions" DROP CONSTRAINT "FK_024d33513a12806d355e41c7a84"`);
        await queryRunner.query(`ALTER TABLE "party_positions" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "party_member_positions" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "meeting_opinions" DROP CONSTRAINT "FK_197bbaf8030304b86ae73cbcc45"`);
        await queryRunner.query(`ALTER TABLE "admission_progress" DROP CONSTRAINT "FK_35840074ee49c531d63aa6bc5e3"`);
        await queryRunner.query(`ALTER TABLE "party_fees" DROP CONSTRAINT "FK_d7d3391431eeb1c26d4fed940cd"`);
        await queryRunner.query(`ALTER TABLE "party_member_positions" DROP CONSTRAINT "FK_13852a503d1ecbc89cebbf61676"`);
        await queryRunner.query(`ALTER TABLE "meeting_attendees" DROP CONSTRAINT "FK_5b652a28dc0c9357eab6f2c5bc5"`);
        await queryRunner.query(`ALTER TABLE "annual_assessments" DROP CONSTRAINT "FK_0342cc197942a79f70c80b59056"`);
        await queryRunner.query(`ALTER TABLE "commendations" DROP CONSTRAINT "FK_b6145c47fe1c9fa7d25dda485af"`);
        await queryRunner.query(`ALTER TABLE "disciplines" DROP CONSTRAINT "FK_ac15435de2541a99ece22304683"`);
        await queryRunner.query(`ALTER TABLE "party_members" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "system_audit_logs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "party_admissions" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TYPE "public"."party_admission_applications_overall_status_enum" RENAME TO "party_admission_applications_overall_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."party_admission_applications_overallstatus_enum" AS ENUM('DRAFT', 'SUBMITTED', 'CHI_UY_REVIEWING', 'NEED_SUPPLEMENT', 'PBT_REVIEWING', 'PBT_REJECTED', 'LOCAL_VERIFICATION_PENDING', 'LOCAL_VERIFICATION_UPLOADED', 'RED_SEAL_CHECKING', 'RED_SEAL_REJECTED', 'RESOLUTION_DRAFTING', 'RESOLUTION_REVIEWING', 'RESOLUTION_REVISION_REQUIRED', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "overallStatus" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "overallStatus" TYPE "public"."party_admission_applications_overallstatus_enum" USING "overallStatus"::"text"::"public"."party_admission_applications_overallstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "overallStatus" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."party_admission_applications_overall_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."party_admission_applications_current_step_code_enum" RENAME TO "party_admission_applications_current_step_code_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."party_admission_applications_currentstepcode_enum" AS ENUM('APPLICATION', 'TRAINING_CLASS', 'VERIFICATION', 'UNION_FEEDBACK', 'FINAL_REVIEW', 'CEREMONY')`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "currentStepCode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "currentStepCode" TYPE "public"."party_admission_applications_currentstepcode_enum" USING "currentStepCode"::"text"::"public"."party_admission_applications_currentstepcode_enum"`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "currentStepCode" SET DEFAULT 'APPLICATION'`);
        await queryRunner.query(`DROP TYPE "public"."party_admission_applications_current_step_code_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."party_admission_applications_current_step_status_enum" RENAME TO "party_admission_applications_current_step_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."party_admission_applications_currentstepstatus_enum" AS ENUM('LOCKED', 'DRAFT', 'OPEN', 'IN_PROGRESS', 'PENDING_APPROVAL', 'COMPLETED', 'RETURNED', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "currentStepStatus" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "currentStepStatus" TYPE "public"."party_admission_applications_currentstepstatus_enum" USING "currentStepStatus"::"text"::"public"."party_admission_applications_currentstepstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "currentStepStatus" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."party_admission_applications_current_step_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "handbook_links" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "handbook_links" DROP CONSTRAINT "FK_08ca89b7c2d7ed362f8cbc46cbc"`);
        await queryRunner.query(`ALTER TABLE "handbooks" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "ai_knowledge_base" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "meeting_sessions" ADD CONSTRAINT "FK_79bd95834df6a4229d47c89ddc9" FOREIGN KEY ("attendee_id") REFERENCES "meeting_attendees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_attendees" ADD CONSTRAINT "FK_8643679c49d7234b266433bc201" FOREIGN KEY ("meeting_id") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_attendees" ADD CONSTRAINT "FK_5b652a28dc0c9357eab6f2c5bc5" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_opinions" ADD CONSTRAINT "FK_b37b346f4b2304af77b536431ab" FOREIGN KEY ("meeting_id") REFERENCES "meetings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_opinions" ADD CONSTRAINT "FK_197bbaf8030304b86ae73cbcc45" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_documents" ADD CONSTRAINT "FK_71ce465252b5177f3a8734a66de" FOREIGN KEY ("meeting_id") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meetings" ADD CONSTRAINT "FK_5d9e6ff1adcbd2c4b1251646a79" FOREIGN KEY ("party_cell_id") REFERENCES "party_cells"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admission_progress" ADD CONSTRAINT "FK_35840074ee49c531d63aa6bc5e3" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "party_fees" ADD CONSTRAINT "FK_d7d3391431eeb1c26d4fed940cd" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annual_assessments" ADD CONSTRAINT "FK_0342cc197942a79f70c80b59056" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commendations" ADD CONSTRAINT "FK_b6145c47fe1c9fa7d25dda485af" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disciplines" ADD CONSTRAINT "FK_ac15435de2541a99ece22304683" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "party_member_positions" ADD CONSTRAINT "FK_13852a503d1ecbc89cebbf61676" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "party_member_positions" ADD CONSTRAINT "FK_024d33513a12806d355e41c7a84" FOREIGN KEY ("position_id") REFERENCES "party_positions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "party_member_positions" ADD CONSTRAINT "FK_2b3335beefdad662520afc33dc8" FOREIGN KEY ("party_cell_id") REFERENCES "party_cells"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "party_members" ADD CONSTRAINT "FK_59fcd9e0286d8c9009113772e5d" FOREIGN KEY ("party_cell_id") REFERENCES "party_cells"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "party_admissions" ADD CONSTRAINT "FK_52e8c691a7e540ba4502ef6e380" FOREIGN KEY ("party_cell_id") REFERENCES "party_cells"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "handbook_links" ADD CONSTRAINT "FK_08ca89b7c2d7ed362f8cbc46cbc" FOREIGN KEY ("handbook_id") REFERENCES "handbooks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_knowledge_base" ADD CONSTRAINT "FK_fa554fa15e67675623cdecf80a1" FOREIGN KEY ("party_cell_id") REFERENCES "party_cells"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ai_knowledge_base" DROP CONSTRAINT "FK_fa554fa15e67675623cdecf80a1"`);
        await queryRunner.query(`ALTER TABLE "handbook_links" DROP CONSTRAINT "FK_08ca89b7c2d7ed362f8cbc46cbc"`);
        await queryRunner.query(`ALTER TABLE "party_admissions" DROP CONSTRAINT "FK_52e8c691a7e540ba4502ef6e380"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "party_members" DROP CONSTRAINT "FK_59fcd9e0286d8c9009113772e5d"`);
        await queryRunner.query(`ALTER TABLE "party_member_positions" DROP CONSTRAINT "FK_2b3335beefdad662520afc33dc8"`);
        await queryRunner.query(`ALTER TABLE "party_member_positions" DROP CONSTRAINT "FK_024d33513a12806d355e41c7a84"`);
        await queryRunner.query(`ALTER TABLE "party_member_positions" DROP CONSTRAINT "FK_13852a503d1ecbc89cebbf61676"`);
        await queryRunner.query(`ALTER TABLE "disciplines" DROP CONSTRAINT "FK_ac15435de2541a99ece22304683"`);
        await queryRunner.query(`ALTER TABLE "commendations" DROP CONSTRAINT "FK_b6145c47fe1c9fa7d25dda485af"`);
        await queryRunner.query(`ALTER TABLE "annual_assessments" DROP CONSTRAINT "FK_0342cc197942a79f70c80b59056"`);
        await queryRunner.query(`ALTER TABLE "party_fees" DROP CONSTRAINT "FK_d7d3391431eeb1c26d4fed940cd"`);
        await queryRunner.query(`ALTER TABLE "admission_progress" DROP CONSTRAINT "FK_35840074ee49c531d63aa6bc5e3"`);
        await queryRunner.query(`ALTER TABLE "meetings" DROP CONSTRAINT "FK_5d9e6ff1adcbd2c4b1251646a79"`);
        await queryRunner.query(`ALTER TABLE "meeting_documents" DROP CONSTRAINT "FK_71ce465252b5177f3a8734a66de"`);
        await queryRunner.query(`ALTER TABLE "meeting_opinions" DROP CONSTRAINT "FK_197bbaf8030304b86ae73cbcc45"`);
        await queryRunner.query(`ALTER TABLE "meeting_opinions" DROP CONSTRAINT "FK_b37b346f4b2304af77b536431ab"`);
        await queryRunner.query(`ALTER TABLE "meeting_attendees" DROP CONSTRAINT "FK_5b652a28dc0c9357eab6f2c5bc5"`);
        await queryRunner.query(`ALTER TABLE "meeting_attendees" DROP CONSTRAINT "FK_8643679c49d7234b266433bc201"`);
        await queryRunner.query(`ALTER TABLE "meeting_sessions" DROP CONSTRAINT "FK_79bd95834df6a4229d47c89ddc9"`);
        await queryRunner.query(`ALTER TABLE "ai_knowledge_base" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "handbooks" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "handbook_links" ADD CONSTRAINT "FK_08ca89b7c2d7ed362f8cbc46cbc" FOREIGN KEY ("handbook_id") REFERENCES "handbooks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "handbook_links" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."party_admission_applications_current_step_status_enum_old" AS ENUM('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "currentStepStatus" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "currentStepStatus" TYPE "public"."party_admission_applications_current_step_status_enum_old" USING "currentStepStatus"::"text"::"public"."party_admission_applications_current_step_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "currentStepStatus" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."party_admission_applications_currentstepstatus_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."party_admission_applications_current_step_status_enum_old" RENAME TO "party_admission_applications_current_step_status_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."party_admission_applications_current_step_code_enum_old" AS ENUM('APPLICATION', 'REVIEW', 'INTERVIEW', 'FINAL')`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "currentStepCode" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "currentStepCode" TYPE "public"."party_admission_applications_current_step_code_enum_old" USING "currentStepCode"::"text"::"public"."party_admission_applications_current_step_code_enum_old"`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "currentStepCode" SET DEFAULT 'APPLICATION'`);
        await queryRunner.query(`DROP TYPE "public"."party_admission_applications_currentstepcode_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."party_admission_applications_current_step_code_enum_old" RENAME TO "party_admission_applications_current_step_code_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."party_admission_applications_overall_status_enum_old" AS ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "overallStatus" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "overallStatus" TYPE "public"."party_admission_applications_overall_status_enum_old" USING "overallStatus"::"text"::"public"."party_admission_applications_overall_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "party_admission_applications" ALTER COLUMN "overallStatus" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."party_admission_applications_overallstatus_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."party_admission_applications_overall_status_enum_old" RENAME TO "party_admission_applications_overall_status_enum"`);
        await queryRunner.query(`ALTER TABLE "party_admissions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "system_audit_logs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "party_members" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "disciplines" ADD CONSTRAINT "FK_ac15435de2541a99ece22304683" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commendations" ADD CONSTRAINT "FK_b6145c47fe1c9fa7d25dda485af" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annual_assessments" ADD CONSTRAINT "FK_0342cc197942a79f70c80b59056" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_attendees" ADD CONSTRAINT "FK_5b652a28dc0c9357eab6f2c5bc5" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "party_member_positions" ADD CONSTRAINT "FK_13852a503d1ecbc89cebbf61676" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "party_fees" ADD CONSTRAINT "FK_d7d3391431eeb1c26d4fed940cd" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admission_progress" ADD CONSTRAINT "FK_35840074ee49c531d63aa6bc5e3" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_opinions" ADD CONSTRAINT "FK_197bbaf8030304b86ae73cbcc45" FOREIGN KEY ("member_id") REFERENCES "party_members"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "party_member_positions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "party_positions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "party_member_positions" ADD CONSTRAINT "FK_024d33513a12806d355e41c7a84" FOREIGN KEY ("position_id") REFERENCES "party_positions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disciplines" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "commendations" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "annual_assessments" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "party_fees" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "admission_progress" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "party_cells" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "party_admissions" ADD CONSTRAINT "FK_52e8c691a7e540ba4502ef6e380" FOREIGN KEY ("party_cell_id") REFERENCES "party_cells"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "party_members" ADD CONSTRAINT "FK_59fcd9e0286d8c9009113772e5d" FOREIGN KEY ("party_cell_id") REFERENCES "party_cells"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meetings" ADD CONSTRAINT "FK_5d9e6ff1adcbd2c4b1251646a79" FOREIGN KEY ("party_cell_id") REFERENCES "party_cells"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_knowledge_base" ADD CONSTRAINT "FK_fa554fa15e67675623cdecf80a1" FOREIGN KEY ("party_cell_id") REFERENCES "party_cells"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "party_member_positions" ADD CONSTRAINT "FK_2b3335beefdad662520afc33dc8" FOREIGN KEY ("party_cell_id") REFERENCES "party_cells"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meetings" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "meeting_documents" ADD CONSTRAINT "FK_71ce465252b5177f3a8734a66de" FOREIGN KEY ("meeting_id") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_attendees" ADD CONSTRAINT "FK_8643679c49d7234b266433bc201" FOREIGN KEY ("meeting_id") REFERENCES "meetings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_opinions" ADD CONSTRAINT "FK_b37b346f4b2304af77b536431ab" FOREIGN KEY ("meeting_id") REFERENCES "meetings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_opinions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "meeting_attendees" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "meeting_sessions" ADD CONSTRAINT "FK_79bd95834df6a4229d47c89ddc9" FOREIGN KEY ("attendee_id") REFERENCES "meeting_attendees"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "meeting_sessions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`DROP INDEX "public"."idx_party_admission_documents_application_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_party_admission_documents_step_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_party_admission_documents_submission_id"`);
        await queryRunner.query(`DROP TABLE "party_admission_documents"`);
        await queryRunner.query(`DROP TYPE "public"."party_admission_documents_documenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_party_admission_step_submissions_application_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_party_admission_step_submissions_step_id"`);
        await queryRunner.query(`DROP TABLE "party_admission_step_submissions"`);
        await queryRunner.query(`DROP TYPE "public"."party_admission_step_submissions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."party_admission_step_submissions_stepcode_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_party_admission_steps_application_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_party_admission_steps_status"`);
        await queryRunner.query(`DROP TABLE "party_admission_steps"`);
        await queryRunner.query(`DROP TYPE "public"."party_admission_steps_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."party_admission_steps_stepcode_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_party_admission_workflow_logs_application_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_party_admission_workflow_logs_step_id"`);
        await queryRunner.query(`DROP TABLE "party_admission_workflow_logs"`);
    }

}
